# Generated by Django 2.0.6 on 2018-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='profiles_through_read', to='comic.ComicBook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='profiles_through_wishlist', to='comic.ComicBook'),
        ),
    ]
