# Generated by Django 2.0.6 on 2018-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='foundation_year',
            field=models.IntegerField(),
        ),
    ]
